---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: routers
  gather_facts: false
  connection: network_cli
  vars:
    student_id: 66070108
    router_name: "{{ inventory_hostname }}"

  tasks:
  - name: DISPLAYING THE RUNNING-CONFIG
    ios_command:
      commands:
        - show running-config
    register: config



  - name: SAVE OUTPUT TO ./backups/
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "backups/show_run_{{ student_id }}_{{ router_name }}.txt"
