---
- name: Configure MOTD on Cisco routers
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    student_id: "{{ student_id }}"
    router_ip: "{{ router_ip }}"
    motd_message: "Authorized users only! Managed by {{ student_id }}"
  tasks:
    - name: Configure MOTD banner
      ios_config:
        lines:
          - banner motd ^{{ motd_message }}^
