---
- name: Configure MOTD on Cisco routers
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    student_id: "{{ student_id }}"
    ansible_host: "{{ router_ip }}"
    motd_message: "Authorized users only! Managed by {{ student_id }}"
  tasks:
    - name: Show which router IP we are connecting to
      debug:
        msg: "Connecting to router {{ ansible_host }} (from router_ip={{ router_ip }})"


    - name: Configure MOTD banner
      ios_config:
        lines:
          - banner motd ^{{ motd_message }}^
